# Generated by Django 5.2.15 on 2026-06-21 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_alter_auditlineitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=12)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=128, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=50)),
                ('redirect_after', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='accounts_oa_state_d21bc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Passkey', max_length=120)),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('aaguid', models.CharField(blank=True, max_length=64)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGlobalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('full_admin', 'Full Admin'), ('site_admin', 'Site Admin'), ('vault_admin', 'Vault Admin'), ('viewer', 'Viewer'), ('audit_reporting', 'Audit & Reporting')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Role',
            },
        ),
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'email'],
                'unique_together': {('provider', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserSiteRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('full_admin', 'Full Admin'), ('site_admin', 'Site Admin'), ('vault_admin', 'Vault Admin'), ('viewer', 'Viewer'), ('audit_reporting', 'Audit & Reporting')], max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='inventory.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Role',
                'unique_together': {('user', 'site')},
            },
        ),
        migrations.CreateModel(
            name='UserVaultRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('full_admin', 'Full Admin'), ('site_admin', 'Site Admin'), ('vault_admin', 'Vault Admin'), ('viewer', 'Viewer'), ('audit_reporting', 'Audit & Reporting')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_roles', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='inventory.vault')),
            ],
            options={
                'verbose_name': 'Vault Role',
                'unique_together': {('user', 'vault')},
            },
        ),
    ]
