# Generated by Django 5.2.15 on 2026-06-20 02:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], max_length=20)),
                ('form_factor', models.CharField(choices=[('bar', 'Bar'), ('coin', 'Coin'), ('round', 'Round'), ('grain', 'Grain / Shot'), ('ingot', 'Ingot'), ('jewelry', 'Jewelry'), ('other', 'Other')], default='coin', max_length=20)),
                ('weight_oz', models.DecimalField(decimal_places=4, max_digits=12)),
                ('purity', models.DecimalField(decimal_places=4, default=0.9999, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchase_price_per_oz', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dealer', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('mint', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('proof', 'Proof'), ('bu', 'BU'), ('au', 'AU'), ('xf', 'XF'), ('vf', 'VF'), ('raw', 'Raw')], default='bu', max_length=10)),
                ('grading_service', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('certificate_number', models.CharField(blank=True, max_length=200)),
                ('vault_location', models.CharField(blank=True, max_length=200)),
                ('insured', models.BooleanField(default=False)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('gold_oz', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('silver_oz', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('platinum_oz', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('palladium_oz', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('certificate', 'Certificate'), ('assay', 'Assay'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.holding')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type', models.CharField(choices=[('home-safe', 'Home Safe'), ('bank-deposit', 'Bank Deposit Box'), ('private-vault', 'Private Vault'), ('cache', 'Cache / Hide'), ('depository', 'Depository')], default='home-safe', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('capacity_oz', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('security_level', models.PositiveSmallIntegerField(default=3)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('fire_rating', models.CharField(blank=True, max_length=100)),
                ('weight_capacity_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='inventory.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.holding')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.site')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.vault')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='inventory.vault'),
        ),
    ]
