# Generated by Django 5.2.15 on 2026-06-20 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_assetcategory_producttype'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='administration.assetcategory'),
        ),
        migrations.AddField(
            model_name='holding',
            name='asset_class',
            field=models.CharField(choices=[('bullion', 'Bullion / Precious Metals'), ('crypto', 'Cryptocurrency'), ('currency', 'Fiat Currency'), ('gem', 'Gems & Jewelry'), ('watch', 'Watches'), ('collectible', 'Collectibles'), ('other', 'Other')], default='bullion', max_length=20),
        ),
        migrations.AddField(
            model_name='holding',
            name='crypto_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='crypto_symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='holding',
            name='encrypted_seed_phrase',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='administration.producttype'),
        ),
        migrations.AddField(
            model_name='holding',
            name='public_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='holding',
            name='reported_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VaultBox-reported USD value for crypto and non-spot assets', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='wallet_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='holding',
            name='wallet_type',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware Wallet'), ('paper', 'Paper Wallet'), ('multisig', 'Multisig'), ('hot', 'Hot Wallet'), ('exchange', 'Exchange Custody'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('bar', 'Bar'), ('coin', 'Coin'), ('round', 'Round'), ('grain', 'Grain / Shot'), ('ingot', 'Ingot'), ('jewelry', 'Jewelry'), ('other', 'Other')], default='coin', max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='metal_type',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('discrepancy_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.vault')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='inventory.auditsession')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('secret_type', models.CharField(choices=[('recovery_code', 'Recovery Code'), ('seed_phrase', 'Seed Phrase'), ('pin', 'PIN / Passphrase'), ('key_location', 'Physical Key Location'), ('safe_combo', 'Safe Combination'), ('qr_backup', 'QR Backup'), ('other', 'Other')], default='other', max_length=20)),
                ('encrypted_content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='inventory.site')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='inventory.vault')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SecretAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='secrets/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('attachment_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('qr_code', 'QR Code'), ('other', 'Other')], default='document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.secret')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_qty', models.PositiveIntegerField()),
                ('counted_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_lines', to='inventory.holding')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.auditsession')),
            ],
            options={
                'ordering': ['holding__name'],
                'unique_together': {('audit', 'holding')},
            },
        ),
    ]
