# Generated by Django 5.2.15 on 2026-06-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_crypto_tokens_and_chain'),
        ('inventory', '0003_dealer_and_asset_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='crypto_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='administration.cryptotokentype'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='metal_type',
            field=models.CharField(blank=True, default='', help_text='Slug from admin Metal Type (gold, silver, copper, …)', max_length=50),
        ),
    ]
