# Generated by Django 5.2.15 on 2026-06-20 04:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_crypto_tokens_and_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('holding', 'Holding'), ('vault', 'Vault'), ('site', 'Site'), ('secret', 'Secret'), ('audit', 'Audit'), ('photo', 'Photo'), ('document', 'Document'), ('admin', 'Admin Config')], max_length=30)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_label', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transact', 'Transact')], max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='holding',
            name='insurance_claim_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='holding',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('stolen', 'Stolen'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='holding',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='transaction_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('stolen', 'Stolen'), ('deleted', 'Deleted')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purchase_price_per_oz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.9999, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='weight_oz',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
