# Generated by Django 5.2.15 on 2026-06-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_holding_status_and_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sub_name',
            field=models.CharField(blank=True, default='', help_text='Optional label (e.g. tube #3, lot A) — product type provides the base name', max_length=200),
        ),
        migrations.AlterField(
            model_name='holding',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
