# Generated by Django 5.1 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_holding_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='storage_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('capsule', 'Capsule'),
                    ('tube', 'Tube'),
                    ('flip', 'Flip'),
                    ('folder', 'Folder'),
                    ('slab', 'Slab'),
                    ('raw', 'Raw / Loose'),
                    ('other', 'Other'),
                ],
                default='',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='holding',
            name='storage_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlineitem',
            name='current_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]