# Generated by Django 5.1 on 2026-06-20

import uuid
from django.db import migrations, models
import django.db.models.deletion


def backfill_line_groups(apps, schema_editor):
    AuditLineItem = apps.get_model('inventory', 'AuditLineItem')
    for item in AuditLineItem.objects.select_related('holding').all():
        if item.holding_id:
            item.group_key = f'holding:{item.holding_id}'
            item.line_kind = 'holding'
            item.display_name = item.holding.name if item.holding_id else ''
            if item.holding and item.holding.product_type_id:
                item.product_type_id = item.holding.product_type_id
            item.save(update_fields=['group_key', 'line_kind', 'product_type_id', 'display_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auditworkflow_audit_type'),
        ('inventory', '0008_auditsession_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlineitem',
            name='group_key',
            field=models.CharField(default='legacy', max_length=120),
        ),
        migrations.AddField(
            model_name='auditlineitem',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='auditlineitem',
            name='line_kind',
            field=models.CharField(
                choices=[('product_type', 'Product Type'), ('holding', 'Holding')],
                default='holding',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='auditlineitem',
            name='product_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='audit_lines',
                to='administration.producttype',
            ),
        ),
        migrations.AlterField(
            model_name='auditlineitem',
            name='holding',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audit_lines',
                to='inventory.holding',
            ),
        ),
        migrations.RunPython(backfill_line_groups, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='auditlineitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='auditlineitem',
            constraint=models.UniqueConstraint(fields=('audit', 'group_key'), name='uniq_audit_group_key'),
        ),
    ]