# Generated by Django 5.2.15 on 2026-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auditlineitem_product_type_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlineitem',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterField(
            model_name='auditlineitem',
            name='group_key',
            field=models.CharField(max_length=120),
        ),
    ]
