# Generated by Django 5.2.15 on 2026-06-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_auditlineitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='value_gain_alert_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when unrealized gain exceeds this %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='value_loss_alert_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when unrealized loss exceeds this %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='audit_interval_days_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='audit_refire_hours_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='audit_reminder_days_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='capacity_alert_threshold_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Notify when vault fill exceeds this % of capacity', max_digits=6, null=True),
        ),
    ]
