# Generated by Django 5.2.15 on 2026-06-20 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_assetcategory_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dealer',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='asset_class',
            field=models.CharField(choices=[('bullion', 'Bullion / Precious Metals'), ('crypto', 'Cryptocurrency'), ('currency', 'Fiat Currency'), ('gem', 'Gems & Jewelry'), ('watch', 'Watches'), ('collectible', 'Collectibles'), ('other', 'Other')], default='bullion', help_text='Which holding asset class this category applies to', max_length=20),
        ),
    ]
