# Generated by Django 5.2.15 on 2026-06-20 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_dealer_and_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTokenType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('chain', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('dogecoin', 'Dogecoin'), ('solana', 'Solana'), ('litecoin', 'Litecoin'), ('other', 'Other')], default='bitcoin', max_length=20)),
                ('coingecko_id', models.CharField(blank=True, help_text='CoinGecko API id for price lookup', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Crypto Token Type',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
