# Generated by Django 5.2.15 on 2026-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auditworkflow_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditworkflow',
            name='audit_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', help_text='Standard = full table; Advanced = one item at a time', max_length=20),
        ),
    ]
