# Generated by Django 5.2.15 on 2026-06-23 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_userprofile_theme_alter_auditworkflow_audit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationoption',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='notificationoption',
            name='apprise_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationoption',
            name='category',
            field=models.CharField(choices=[('audit', 'Audits'), ('admin', 'Admin & Users'), ('market', 'Spot / Market'), ('asset', 'Assets & Value'), ('activity', 'Activity Log')], default='asset', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationoption',
            name='is_system_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationoption',
            name='refire_interval_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apprise_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='event_type',
            field=models.CharField(choices=[('audit_due', 'Audit Due'), ('audit_overdue', 'Audit Overdue'), ('audit_completed', 'Audit Completed'), ('audit_completed_issues', 'Audit Completed (Issues)'), ('audit_canceled', 'Audit Canceled'), ('signup_request', 'Signup Request'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('passkey_added', 'Passkey Added'), ('passkey_removed', 'Passkey Removed'), ('price_change', 'Spot/Market Price Change'), ('asset_value_gain', 'Unrealized Gain Threshold'), ('asset_value_loss', 'Unrealized Loss Threshold'), ('capacity_warning', 'Vault Capacity Warning'), ('new_acquisition', 'New Acquisition'), ('insurance_expiry', 'Insurance Expiry'), ('activity_create', 'Activity: Created'), ('activity_update', 'Activity: Updated'), ('activity_delete', 'Activity: Deleted'), ('activity_transact', 'Activity: Transaction')], max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='RoleNotificationDefault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('full_admin', 'Full Admin'), ('site_admin', 'Site Admin'), ('vault_admin', 'Vault Admin'), ('viewer', 'Viewer'), ('audit_reporting', 'Audit / Reporting')], max_length=30)),
                ('event_type', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('in_app', models.BooleanField(blank=True, null=True)),
                ('email', models.BooleanField(blank=True, null=True)),
                ('apprise', models.BooleanField(blank=True, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refire_interval_hours', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['role', 'event_type'],
                'unique_together': {('role', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'dismissed_at', '-created_at'], name='administrat_user_id_45a058_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('in_app', models.BooleanField(blank=True, null=True)),
                ('email', models.BooleanField(blank=True, null=True)),
                ('apprise', models.BooleanField(blank=True, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refire_interval_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_type'],
                'unique_together': {('user', 'event_type')},
            },
        ),
    ]
