# Generated by Django 5.2.15 on 2026-06-23 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_notifications_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('pre_restore', 'Pre-restore safety')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('include_media', models.BooleanField(default=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('rclone_remote_id', models.CharField(blank=True, max_length=100)),
                ('rclone_uploaded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
